# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir K:/MostFrequentlyNeeded___2014/Education2011/2015_2016/SecondSemester/CR/AulasTeoricas/Aula2_22Feb2016/ToElearningProjects/SompleSimulation/SompleSimulation.cache/wt [current_project]
set_property parent.project_path K:/MostFrequentlyNeeded___2014/Education2011/2015_2016/SecondSemester/CR/AulasTeoricas/Aula2_22Feb2016/ToElearningProjects/SompleSimulation/SompleSimulation.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib K:/MostFrequentlyNeeded___2014/Education2011/2015_2016/SecondSemester/CR/AulasTeoricas/Aula2_22Feb2016/ToElearningProjects/SompleSimulation/SompleSimulation.srcs/sources_1/new/ForSim.vhd
read_xdc K:/MostFrequentlyNeeded___2014/Education2011/2015_2016/SecondSemester/CR/AulasTeoricas/Aula2_22Feb2016/ToElearningProjects/SompleSimulation/SompleSimulation.srcs/constrs_1/imports/Aula1_15Feb2016/Nexys4_Master.xdc
set_property used_in_implementation false [get_files K:/MostFrequentlyNeeded___2014/Education2011/2015_2016/SecondSemester/CR/AulasTeoricas/Aula2_22Feb2016/ToElearningProjects/SompleSimulation/SompleSimulation.srcs/constrs_1/imports/Aula1_15Feb2016/Nexys4_Master.xdc]

synth_design -top ForSim -part xc7a100tcsg324-1
write_checkpoint -noxdef ForSim.dcp
catch { report_utilization -file ForSim_utilization_synth.rpt -pb ForSim_utilization_synth.pb }
