# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir K:/MostFrequentlyNeeded___2014/Education2011/2015_2016/SecondSemester/CR/AulasTeoricas/Aula1_15Feb2016/Proj1/UsingClock/UsingClock.cache/wt [current_project]
set_property parent.project_path K:/MostFrequentlyNeeded___2014/Education2011/2015_2016/SecondSemester/CR/AulasTeoricas/Aula1_15Feb2016/Proj1/UsingClock/UsingClock.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  K:/MostFrequentlyNeeded___2014/Education2011/2015_2016/SecondSemester/CR/AulasTeoricas/Aula1_15Feb2016/Proj1/UsingClock/UsingClock.srcs/sources_1/imports/FirstTrivial/Clock_divider.vhd
  K:/MostFrequentlyNeeded___2014/Education2011/2015_2016/SecondSemester/CR/AulasTeoricas/Aula1_15Feb2016/Proj1/UsingClock/UsingClock.srcs/sources_1/new/SDR_first.vhd
}
read_xdc K:/MostFrequentlyNeeded___2014/Education2011/2015_2016/SecondSemester/CR/AulasTeoricas/Aula1_15Feb2016/Proj1/UsingClock/UsingClock.srcs/constrs_1/new/SDR_const.xdc
set_property used_in_implementation false [get_files K:/MostFrequentlyNeeded___2014/Education2011/2015_2016/SecondSemester/CR/AulasTeoricas/Aula1_15Feb2016/Proj1/UsingClock/UsingClock.srcs/constrs_1/new/SDR_const.xdc]

synth_design -top TopTrivial -part xc7a100tcsg324-3
write_checkpoint -noxdef TopTrivial.dcp
catch { report_utilization -file TopTrivial_utilization_synth.rpt -pb TopTrivial_utilization_synth.pb }
