# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/MostFrequentlyNeeded___2014/Education2011/2014_2015/SecondSemester/CR/AllProjectsThat were_Used_for_CR_in_2014_2015/SDR_P/1/UsingSegmentDisplays/UsingSegmentDisplays.cache/wt} [current_project]
set_property parent.project_path {E:/MostFrequentlyNeeded___2014/Education2011/2014_2015/SecondSemester/CR/AllProjectsThat were_Used_for_CR_in_2014_2015/SDR_P/1/UsingSegmentDisplays/UsingSegmentDisplays.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  {E:/MostFrequentlyNeeded___2014/Education2011/2014_2015/SecondSemester/CR/AllProjectsThat were_Used_for_CR_in_2014_2015/SDR_P/1/UsingSegmentDisplays/UsingSegmentDisplays.srcs/sources_1/imports/Binario_BCD/SegmentDecoder.vhd}
  {E:/MostFrequentlyNeeded___2014/Education2011/2014_2015/SecondSemester/CR/AllProjectsThat were_Used_for_CR_in_2014_2015/SDR_P/1/UsingSegmentDisplays/UsingSegmentDisplays.srcs/sources_1/imports/Binario_BCD/DidplayControl.vhd}
  {E:/MostFrequentlyNeeded___2014/Education2011/2014_2015/SecondSemester/CR/AllProjectsThat were_Used_for_CR_in_2014_2015/SDR_P/1/UsingSegmentDisplays/UsingSegmentDisplays.srcs/sources_1/imports/Binario_BCD/Clock_divider.vhd}
  {E:/MostFrequentlyNeeded___2014/Education2011/2014_2015/SecondSemester/CR/AllProjectsThat were_Used_for_CR_in_2014_2015/SDR_P/1/UsingSegmentDisplays/UsingSegmentDisplays.srcs/sources_1/imports/Binario_BCD/Binary_to_BCD16.vhd}
  {E:/MostFrequentlyNeeded___2014/Education2011/2014_2015/SecondSemester/CR/AllProjectsThat were_Used_for_CR_in_2014_2015/SDR_P/1/UsingSegmentDisplays/UsingSegmentDisplays.srcs/sources_1/imports/Binario_BCD/TopTrivial.vhd}
}
read_xdc {{E:/MostFrequentlyNeeded___2014/Education2011/2014_2015/SecondSemester/CR/AllProjectsThat were_Used_for_CR_in_2014_2015/SDR_P/1/UsingSegmentDisplays/UsingSegmentDisplays.srcs/constrs_1/imports/new/SDR_const.xdc}}
set_property used_in_implementation false [get_files {{E:/MostFrequentlyNeeded___2014/Education2011/2014_2015/SecondSemester/CR/AllProjectsThat were_Used_for_CR_in_2014_2015/SDR_P/1/UsingSegmentDisplays/UsingSegmentDisplays.srcs/constrs_1/imports/new/SDR_const.xdc}}]

synth_design -top TopTrivial -part xc7a100tcsg324-3
write_checkpoint -noxdef TopTrivial.dcp
catch { report_utilization -file TopTrivial_utilization_synth.rpt -pb TopTrivial_utilization_synth.pb }
