# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {Y:/Development/ect_ua/reconfigurable-computation/Rafael/Aula 2/Pratica/aula/aula.cache/wt} [current_project]
set_property parent.project_path {Y:/Development/ect_ua/reconfigurable-computation/Rafael/Aula 2/Pratica/aula/aula.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {{Y:/Development/ect_ua/reconfigurable-computation/Rafael/Aula 2/Pratica/aula/aula.srcs/sources_1/new/ex22.vhd}}
read_xdc Y:/Development/ect_ua/reconfigurable-computation/Rafael/Nexys4_Master.xdc
set_property used_in_implementation false [get_files Y:/Development/ect_ua/reconfigurable-computation/Rafael/Nexys4_Master.xdc]

synth_design -top ex22 -part xc7a100tcsg324-1
write_checkpoint -noxdef ex22.dcp
catch { report_utilization -file ex22_utilization_synth.rpt -pb ex22_utilization_synth.pb }
