# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/Desktop/StudyWorkTeam/4ano/2Semestre/CR/Aula05/project53/project53.cache/wt [current_project]
set_property parent.project_path Z:/Desktop/StudyWorkTeam/4ano/2Semestre/CR/Aula05/project53/project53.xpr [current_project]
set_property default_lib work [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library work {
  Z:/Desktop/StudyWorkTeam/4ano/2Semestre/CR/Aula05/exercicio53/exercicio53.srcs/sources_1/imports/new/segment_decoder.vhd
  Z:/Desktop/StudyWorkTeam/4ano/2Semestre/CR/Aula05/exercicio53/exercicio53.srcs/sources_1/imports/new/Random_number_generator.vhd
  Z:/Desktop/StudyWorkTeam/4ano/2Semestre/CR/Aula05/exercicio53/exercicio53.srcs/sources_1/imports/new/Ex51_aula5.vhd
  Z:/Desktop/StudyWorkTeam/4ano/2Semestre/CR/Aula05/exercicio53/exercicio53.srcs/sources_1/imports/new/disp.vhd
  Z:/Desktop/StudyWorkTeam/4ano/2Semestre/CR/Aula05/exercicio53/exercicio53.srcs/sources_1/new/Ex53_aula5.vhd
}
read_xdc Z:/Desktop/StudyWorkTeam/4ano/2Semestre/CR/Aula04/ex3/ex3.srcs/constrs_1/imports/Rodrigo/Nexys4_Master.xdc
set_property used_in_implementation false [get_files Z:/Desktop/StudyWorkTeam/4ano/2Semestre/CR/Aula04/ex3/ex3.srcs/constrs_1/imports/Rodrigo/Nexys4_Master.xdc]

synth_design -top Ex53_aula5 -part xc7a100tcsg324-1
write_checkpoint -noxdef Ex53_aula5.dcp
catch { report_utilization -file Ex53_aula5_utilization_synth.rpt -pb Ex53_aula5_utilization_synth.pb }
