# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-3
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir I:/SDR_P/1/SynSym/SynSym.cache/wt [current_project]
set_property parent.project_path I:/SDR_P/1/SynSym/SynSym.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib I:/SDR_P/1/SynSym/SynSym.srcs/sources_1/new/Counter.vhd
read_xdc I:/SDR_P/1/SynSym/SynSym.srcs/constrs_1/imports/new/SDR_const.xdc
set_property used_in_implementation false [get_files I:/SDR_P/1/SynSym/SynSym.srcs/constrs_1/imports/new/SDR_const.xdc]

catch { write_hwdef -file Counter.hwdef }
synth_design -top Counter -part xc7a100tcsg324-3
write_checkpoint -noxdef Counter.dcp
catch { report_utilization -file Counter_utilization_synth.rpt -pb Counter_utilization_synth.pb }
